const images = {
  splash: require('../assets/Images/ic_splash_bg.png'),
  tutorial1: require('../assets/Images/ic_loginoption_bg.png'),
  tutorial2: require('../assets/Images/ic_loginoption_explore_bg.png'),
  tutorial3: require('../assets/Images/ic_loginoption_connect_bg.png'),
  fb: require('../assets/Images/ic_loginoption_fb.png'),
  swipe: require('../assets/Images/ic_loginoption_swipe.png'),
  linkedin: require('../assets/Images/linkedin.jpg'),
  emailloginimage: require('../assets/Images/ic_email_login_bg.png'),
  key: require('../assets/Images/ic_forgot_password_illustration.png'),
  back: require('../assets/Images/left-arrow.png'),
  threelines: require('../assets/Images/ic_home_menu.png'),
  searchIcon: require('../assets/Images/ic_home_search.png'),
  homeEnable: require('../assets/Images/ic_home_enable_event.png'),
  homeSettings: require('../assets/Images/ic_home_enable_map.png'),
  searchPin: require('../assets/Images/ic_home_search_pin.png'),
  marker: require('../assets/Images/ic_home_people_pin.png'),
  share: require('../assets/Images/ic_share.png'),
  delete: require('../assets/Images/ic_settings_delete.png'),
  markerImage: require('../assets/Images/ic_pink_pin_glass.png'),
  edit: require('../assets/Images/ic_signup_camera.png'),
  placeHolder: require('../assets/Images/icPicPlaceholder.png'),
  sideMenu: require('../assets/Images/icSideMenu.png'),
  chatBack: require('../assets/Images/icBackBtn.png'),
  send: require('../assets/Images/icSend.png'),
  play: require('../assets/Images/play.png'),
  next: require('../assets/Images/next.png'),
  pause: require('../assets/Images/pause.png'),
  previous: require('../assets/Images/previous.png'),
};
export default images;
